# Generated by Django 4.1.3 on 2022-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
