# Generated by Django 4.1.3 on 2022-12-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_moto_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='origen',
        ),
    ]
