# Generated by Django 4.1.2 on 2022-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_automovil_origen_remove_moto_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
