# Generated by Django 4.1.2 on 2022-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_automovil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='imagen',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
