# Generated by Django 4.1.2 on 2022-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_moto_imagen_alter_automovil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
