# Generated by Django 4.1.2 on 2022-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_automovil_autor_moto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
