# Generated by Django 4.1.3 on 2022-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('email_usuario', models.EmailField(max_length=80)),
                ('password_usuario', models.CharField(max_length=25)),
            ],
        ),
    ]
