# Generated by Django 4.1.3 on 2022-12-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(max_length=1000),
        ),
    ]
