# Generated by Django 4.1.3 on 2022-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_alter_mensajes_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
